spring.application.name=Backend

spring.datasource.url=jdbc:postgresql://localhost:5433/cloudvault
spring.jpa.open-in-view=false
minio.endpoint=http://localhost:9000
minio.bucket-name=cloudvault-files
spring.config.import=optional:classpath:application-local.properties